### ISSUE TITLE
Создать базу данных бота в PostgreSQL

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#1]
Иван - сделать базу данных в PostgreSQL с использованием графического редактора dbdesigner. 
Создать таблицы для преподавателей и учеников. 
Сделать базу тут: https://erd.dbdesigner.net/

**Comment by Kozyrev-Ivan** [comment]
База данных для нахождения учеников и репетиторов была создана. Посмотреть итоговый результат может в файле "kursachtables.sql" и "ERD.png"
