### ISSUE TITLE
Создание бота в BotFather

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#2]
Миша - в телеграмме заходишь в BotFather и создаешь ключ для бота. 

Я - создаю картинку для бота. И загружаю ее на аватарку самого бота

**Comment by marm1kh** [comment]
Ключ: 6635411143:AAGgN4ZPdhcjcd0Mw27_XCjSVQxaHAtwyw8. Ссылка: https://t.me/Repetitors_here_bot
