### ISSUE TITLE
Сделать диаграммы

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#3]
Сделать следующие диаграммы: 
Иван
Архитектурная диаграмма
Функциональная диаграмма UML 
Диаграмма последовательности
Роман
Сделать диаграмму пакетов UML для своего продукта
Оформить диаграмму физической модели

**Comment by Kozyrev-Ivan** [comment]
Была добавлена диаграмма последовательности и функциональная диаграмма UML.

**Comment by rvoznak** [comment]
Были сделаны остальные диаграммы и добавлены Иваном в репозиторий
