### ISSUE TITLE
Выгрузка БД в pgAdmin4, а также начало разработки первых функций

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#4]
Иван - Выгрузить Базу данных в pgAdmin4. Устранить ошибки.
Роман и Михаил - Функция регистрации в Боте телеграмма. 
Разделение на преподавателя и ученика, а так же заполнение краткой информации о боте.

**Comment by marm1kh** [comment]
Функции регистрации были реализованы. Добавлены в Bot1.

**Comment by Kozyrev-Ivan** [comment]
База данных была добавлена в pgadmin4. Также была создана таблица "table_students"

**Comment by rvoznak** [comment]
Реализованы функции удаления аккаунта в C# из базы данных.
