### ISSUE TITLE
Создание функций для Базы данных. 

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#5]
Иван - Создание функций для базы данных 
На языке PostgreSQL сделать:
1) Функция заполнения строк для преподавателя и для ученика. 
2) Функция для отображения аккаунта преподавателя.
3) Функция для отображения аккаунта ученика.
4) Функция для удаления аккаунтов ученика и преподавателей.

**Comment by Kozyrev-Ivan** [comment]
Все функции созданы. Код находится в файле "functions_and_procedures.txt"
