### ISSUE TITLE
Выгрузка функций C#

### ISSUE THREAD

**Issue by rvoznak** [rvoznak/Kursach_BKM#6]
1) Сделать функцию регистрации пользователей
Для ученика и преподавателя отдельно
2) Записать их в базу данных
3) Для ученика сделать функцию вывода преподавателей из базы данных
4) Написать функцию для удаления пользователей из базы данных.
5) Реализовать общение между преподавателями

**Comment by marm1kh** [comment]
1. Регистрация ученика и преподавателя реализованы.
2. Профили сохраняются в базе данных.
3. У ученика есть возможность получить информацию о всех преподавателях.
4. Каждый пользователь может удалить свой аккаунт.
5. Общение между пользователями реализовано.
