### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by SergeyMirvoda** [rvoznak/Kursach_BKM#8]
![изображение](https://github.com/rvoznak/Kursach_BKM/assets/286948/4f161406-e99f-423b-97a5-fc132e52d550)

**Comment by SergeyMirvoda** [comment]
Первая диаграмма слишком сложная для вИдения.
Упростите её -- нужно что-то иллюстрирующее основную идею.

Сама диаграмма хорошая, исправьте ошибки и перенесите её в раздел проектирования

**Comment by SergeyMirvoda** [comment]
На вашей архитектурной диаграмме не видно ничего.
пользователь это бот?
или это человек?

Архитекутра посложнее. Клиент отправляет запрос боту, бот обрабатывает и отправляет сервер, сервер базе и т.д.
на диаграмме это должно быть. Как минимум все межпроцессные взаимодействия нужно показать

**Comment by SergeyMirvoda** [comment]
К диаграммам БД нужны пояснения. Таблицу со списком колонок их типом и комментарием в котором кратко назначение

**Comment by SergeyMirvoda** [comment]
В приложение добавить код

**Comment by SergeyMirvoda** [comment]
в целом ОК, исправляйте замечания

**Comment by rvoznak** [comment]
Замечания были устранены
